server:
  port: 8761

spring:
  application:
    name: service-registry   # <---- add this

eureka:
  instance:
    hostname: localhost
  client:
    register-with-eureka: false
    fetch-registry: false
